### ISSUE TITLE
Help requested: Can't get the webserver up

### ISSUE THREAD

**Issue by chamsters** [celsworth/octolux#13]
Hey Chris,

I've been trying to port my octolux onto a raspberry pi. Gone through all the instructions, even got the server up but the page is still unaccessible. Clearly I've missed something!!

From octolux_server.service log:

> Sep 20 14:54:14 raspberrypi systemd[1]: Started Octolux Server.
> Sep 20 14:59:20 raspberrypi server.rb[435]: [2021-09-20 14:59:20] INFO  WEBrick 1.4.2
> Sep 20 14:59:20 raspberrypi server.rb[435]: [2021-09-20 14:59:20] INFO  ruby 2.5.5 (2019-03-15) [arm-linux-gnueabihf]
> Sep 20 14:59:20 raspberrypi server.rb[435]: [2021-09-20 14:59:20] INFO  WEBrick::HTTPServer#start: pid=435 port=4346
> Sep 20 15:03:05 raspberrypi server.rb[435]: 192.168.1.176 - - [20/Sep/2021:15:03:05 BST] "GET / HTTP/1.1" 404 0
> Sep 20 15:03:05 raspberrypi server.rb[435]: - -> /

For reference, I've tried to load the site using http://192.168.1.17:4346 which yields a 404 error - you can see this in the last 2 lines of the log. 

Far as I can see no firewalls running that could be blocking it - and that would yield a different error. 

Trying to run via sudo ruby server.rb yields the same error on the console as the two lines above - 404 error. Running the ruby scripts in the test folder (e.g. toggle ac charge) DOES work, so it is communicating with my inverter.

Any idea what I'm missing? 

Thanks!

**Comment by chamsters** [comment]
@celsworth any insights would be massively appreciated!

So far I've tried multiple full reinstalls, as well as running ruby with different user permissions as well as changing permissions of the octolux folder - no mater what I did I get a 404. Wondering if it's looking for the install in your pi folder rather than in the folder I have it in - although I don't see any deltas in the other instance i'm running on another server, under the same folder structure too!

**Comment by celsworth** [comment]
Hey :)

Sorry its been a while since I've looked at this server stuff, had to go refresh my memory on what it actually does ;)

So, you're trying to visit it in a web browser and just open the homepage? The problem is, the web server doesn't have a page there, which is why you get 404.. this is normal.

The web server is defined at https://github.com/celsworth/octolux/blob/master/lib/app.rb and you can see how the routes are defined; basically you should be able to `GET /api/inputs` and `GET /api/registers` and get a reply of JSON.

**Comment by chamsters** [comment]
Hm so the way I had bodged things together in the original octolux I had
installed was reading this one line of data that was presented on a
placeholder page when you opened that website on :4346. Most of the page
was just placeholder / "this doesn't do anything" messages but there was a
bit of JSON code that appeared in the middle, which I had a php script
nabbing, parsing, and doing all sorts of fun stuff with.

I'll try out the /api/inputs route instead, see if I have any luck - thanks!

**Comment by chamsters** [comment]
This was a 5 minute fix - thank you :)
