### ISSUE TITLE
Fine for a year+, sudden connection issues 

### ISSUE THREAD

**Issue by chamsters** [celsworth/octolux#14]
Hi there!

I've had no issues at all with octolux for ages until a couple of days ago where it's stopped connecting to my inverter.

13: from /var/www/html/octolux/test/ac_charge_off.rb:11:in `<main>'
        12: from /var/www/html/octolux/lib/lux_controller.rb:41:in `charge'
        11: from /var/www/html/octolux/lib/lux_controller.rb:96:in `update_register'
        10: from /var/www/html/octolux/lib/lux_controller.rb:112:in `read_register'
         9: from /var/www/html/octolux/lib/lux_socket.rb:17:in `write'
         8: from /var/www/html/octolux/lib/lux_socket.rb:63:in `socket'
         7: from /usr/lib/ruby/2.5.0/socket.rb:631:in `tcp'
         6: from /usr/lib/ruby/2.5.0/socket.rb:227:in `foreach'
         5: from /usr/lib/ruby/2.5.0/socket.rb:227:in `each'
         4: from /usr/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
         3: from /usr/lib/ruby/2.5.0/socket.rb:137:in `connect'
         2: from /usr/lib/ruby/2.5.0/socket.rb:56:in `connect_internal'
         1: from /usr/lib/ruby/2.5.0/socket.rb:1213:in `connect_nonblock'
/usr/lib/ruby/2.5.0/socket.rb:1213:in `__connect_nonblock': No route to host - connect(2) for 192.168.1.88:4346 (Errno::EHOSTUNREACH)

The IP address is correct, I'm able to log into the IP address and see network settings, no firewalls or anything, and I've tried rebooting the full system.

Any other ideas??

Thanks!

**Comment by celsworth** [comment]
Hmm, when you check the network settings page of the inverter, does it still show "TCP Server" and port 4346 under the second set of settings? There's a slim chance they've been changed (by Luxpower possibly, I think they can change lots of things remotely). I'd advise on using port 8000 now though, then your inverter remains compatible with using the "local" mode of their app.

If thats still fine, have you checked obvious things like pinging the IP from the machine octolux is running on, and telnetting to the IP:port? This seems a bit odd, the error is quite a low-level OS error saying it just can't connect to the inverter, so there's not a great deal Octolux can do about that :o

**Comment by chamsters** [comment]
Appreciate the inputs! Weirdly when trying to ping the inverter IP from the pi I was getting no response - yet every other IP worked. I could ping the inverter IP from another computer. Yet, no firewalls. Mysterious!?

I rebooted the whole network and changed the port to 8000 - it all appears to be working again. Weird glitch?!
