### ISSUE TITLE
SSL certificate expired? 

### ISSUE THREAD

**Issue by chamsters** [celsworth/octolux#5]
Hi there! 

Seem to have a certificate issue since 3pm today? Any ideas? 

'
	from /octolux/octolux.rb:9:in `<main>'
/usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from

**Comment by celsworth** [comment]
Looks like this might be Octopus letting a certificate expire. If you're on the Octopus Agile forum there's a thread about it - https://forum.octopus.energy/t/certificate-expired/976

**Comment by chamsters** [comment]
Ah phew. I started looking at all the changes you've made to your code that I haven't merged which wasn't very enjoyable :)

I can't access that forum unfortunately - just asked for permissions to it. 

Hopefully it should be resolved soon - although if there's an ignore option you can share (assuming it is a 2 min hack job) then I'd really appreciate that!

**Comment by celsworth** [comment]
I haven't tried this (I'm actually sans inverter and solar setup at the moment, having just moved!) but try this changing the `http` method near the bottom of `lib/octopus.rb` so it looks like this (the `verify_mode` line has been added, nothing else changed):

```ruby
  def http
    @http ||= Net::HTTP.new(url.host, url.port).tap do |http|
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE    end
  end
```

**Comment by chamsters** [comment]
> I haven't tried this (I'm actually sans inverter and solar setup at the moment, having just moved!) but try changing the `http` method near the bottom of `lib/octopus.rb` so it looks like this (the `verify_mode` line has been added, nothing else changed):
> 
> ```ruby
>   def http
>     @http ||= Net::HTTP.new(url.host, url.port).tap do |http|
>       http.use_ssl = true
>       http.verify_mode = OpenSSL::SSL::VERIFY_NONE
>     end
>   end
> ```

Yep, that's fixed it - thanks!

haha you must be dying to get everything set up again??
